parser for timetable v0.1
danilasokolov0103/Chayka_bot pull request #4
Opened 2019-12-17 15:59 UTC by danilasokolov0103

2019-12-17 18:41 UTC, sobrabd requested changes

2019-12-17 18:41 UTC, sobrabd commented on parser.py
> +def get_all_rooms_scheldue():
до этого момента все было неплохо, но тут, как мне кажется можно более лаконично переписать, может быть удасться через циклы, сначала собрать все необходимые данные в список, а потом по нему пройтись циклом.
типа [{"1":  "room0"}, { "1", "room1"} ...] хорошо бы чтобы это собиралось отдельной функцией.
for room in rooms:

2019-12-17 18:41 UTC, sobrabd commented on parser.py
> +    data_all = data_room1 + data_room1_1 + data_room2 + data_room2_1 + data_room3 + data_room3_1 + data_room4 + data_room4_1
тоже нужно как-то преобразовать через, занести в цикл и через extend или через  +=
data += room_data

2019-12-17 18:41 UTC, sobrabd commented on parser.py
> +    get_all_rooms_scheldue()
Получается все спарсить с первого раза, или нужно несколько раз запускать?

2019-12-18 23:45 UTC, Leramt commented on parser.py
> +def get_room_scheldue(html, room_number, room_number_parsing):
schedule только

2019-12-18 23:47 UTC, Leramt commented on parser.py
> +        browser.get('https://chaykastudia.ru/onlajn-bronirovanie/repeticionnye-komnaty/')
может есть смысл вынести переменную html в отдельный файл config.py как в лекциях, туда же в последствии записать ключ к боту и путь к базе данных

2019-12-19 22:56 UTC, Leramt approved these changes

2019-12-20 09:27 UTC, closed without merging